name: CI build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build esp32-poe-iso
        run: pio run -e esp32-poe-iso

      - name: Build spiffs.bin
        run: pio run -t buildfs -e esp32-poe-iso

      - name: Build firmware package
        run: cwd

      - name: Upload firmware package Artifact
        run: ls